import React, { useRef } from "react";
import { Modal } from "react-bootstrap";
import { FaPrint, FaDownload } from "react-icons/fa";

const EscrowAgreementModal = ({ show, onClose, transaction }) => {
  const agreementRef = useRef(null);

  const agreementDate = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const shortId = transaction?.transaction_id?.slice(0, 12) || "—";
  const fullTransactionId = transaction?.transaction_id || "—";
  const buyerEmail = transaction?.buyer_email || "—";
  const vendorName = transaction?.vendor_name || "—";
  const vendorEmail = transaction?.vendor_email || "—";
  const products = transaction?.products || [];
  const sumTotal = transaction?.sum_total || 0;
  const transactionTotal = transaction?.transaction_total || 0;
  const commission = transactionTotal - sumTotal;
  const deliveryAddress = transaction?.delivery_address || "—";

  const deliveryDisplay = transaction?.expected_delivery_date
    ? new Date(transaction.expected_delivery_date).toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
      })
    : transaction?.expected_delivery_range || "As agreed between parties";

  // Print the agreement
  const handlePrint = () => {
    const printContent = agreementRef.current;
    const originalTitle = document.title;

    // Set title for print
    document.title = `Escrow_Agreement_${fullTransactionId}`;

    const printWindow = window.open("", "_blank", "width=800,height=600");
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>MyDoshBox Escrow Agreement - ${fullTransactionId}</title>
          <style>
            body {
              font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
              line-height: 1.6;
              color: #333;
              max-width: 900px;
              margin: 0 auto;
              padding: 40px 20px;
            }
            .header {
              text-align: center;
              margin-bottom: 30px;
              padding-bottom: 20px;
              border-bottom: 2px solid #006747;
            }
            .logo {
              font-size: 24px;
              font-weight: bold;
              color: #006747;
              margin-bottom: 10px;
            }
            .title {
              font-size: 20px;
              font-weight: 600;
              margin: 20px 0;
            }
            .meta-strip {
              display: flex;
              justify-content: space-between;
              background: #f5f5f5;
              padding: 15px;
              margin: 20px 0;
              border-radius: 5px;
            }
            .party-box {
              background: #f9fafb;
              border: 1px solid #e5e7eb;
              padding: 12px;
              margin: 10px 0;
              border-radius: 5px;
            }
            .items-table {
              width: 100%;
              border-collapse: collapse;
              margin: 15px 0;
            }
            .items-table th, .items-table td {
              border: 1px solid #ddd;
              padding: 8px;
              text-align: left;
            }
            .items-table th {
              background-color: #f5f5f5;
            }
            .clause {
              margin: 15px 0;
            }
            .clause-title {
              font-weight: 600;
              margin-bottom: 5px;
            }
            .footer {
              margin-top: 40px;
              text-align: center;
              font-size: 12px;
              color: #666;
              border-top: 1px solid #ddd;
              padding-top: 20px;
            }
            @media print {
              body {
                padding: 0;
                margin: 0;
              }
              button {
                display: none;
              }
            }
          </style>
        </head>
        <body>
          <div class="header">
            <div class="logo">MyDoshBox</div>
            <div class="title">Escrow Agreement</div>
          </div>
          ${printContent ? printContent.innerHTML : ""}
          <div class="footer">
            Generated by MyDoshBox · ${agreementDate}<br/>
            Transaction ID: ${fullTransactionId}
          </div>
        </body>
      </html>
    `);

    printWindow.document.close();
    printWindow.print();

    // Restore original title
    document.title = originalTitle;
  };

  // Save as PDF (download)
  const handleSaveAsPDF = () => {
    const printContent = agreementRef.current;
    const originalTitle = document.title;

    document.title = `Escrow_Agreement_${fullTransactionId}`;

    const printWindow = window.open("", "_blank", "width=800,height=600");
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>MyDoshBox Escrow Agreement - ${fullTransactionId}</title>
          <style>
            body {
              font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
              line-height: 1.6;
              color: #333;
              max-width: 900px;
              margin: 0 auto;
              padding: 40px 20px;
            }
            .header {
              text-align: center;
              margin-bottom: 30px;
              padding-bottom: 20px;
              border-bottom: 2px solid #006747;
            }
            .logo {
              font-size: 24px;
              font-weight: bold;
              color: #006747;
              margin-bottom: 10px;
            }
            .title {
              font-size: 20px;
              font-weight: 600;
              margin: 20px 0;
            }
            .meta-strip {
              display: flex;
              justify-content: space-between;
              background: #f5f5f5;
              padding: 15px;
              margin: 20px 0;
              border-radius: 5px;
            }
            .party-box {
              background: #f9fafb;
              border: 1px solid #e5e7eb;
              padding: 12px;
              margin: 10px 0;
              border-radius: 5px;
            }
            .items-table {
              width: 100%;
              border-collapse: collapse;
              margin: 15px 0;
            }
            .items-table th, .items-table td {
              border: 1px solid #ddd;
              padding: 8px;
              text-align: left;
            }
            .items-table th {
              background-color: #f5f5f5;
            }
            .clause {
              margin: 15px 0;
            }
            .clause-title {
              font-weight: 600;
              margin-bottom: 5px;
            }
            .footer {
              margin-top: 40px;
              text-align: center;
              font-size: 12px;
              color: #666;
              border-top: 1px solid #ddd;
              padding-top: 20px;
            }
          </style>
        </head>
        <body>
          <div class="header">
            <div class="logo">MyDoshBox</div>
            <div class="title">Escrow Agreement</div>
          </div>
          ${printContent ? printContent.innerHTML : ""}
          <div class="footer">
            Generated by MyDoshBox · ${agreementDate}<br/>
            Transaction ID: ${fullTransactionId}
          </div>
        </body>
      </html>
    `);

    printWindow.document.close();
    printWindow.print();
    printWindow.onafterprint = () => {
      printWindow.close();
    };

    document.title = originalTitle;
  };

  return (
    <Modal show={show} onHide={onClose} size="lg" centered>
      <Modal.Header
        closeButton
        style={{ background: "#006747", border: "none", padding: "16px 24px" }}
      >
        <Modal.Title style={{ display: "flex", alignItems: "center", gap: 10 }}>
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none">
            <rect
              x="3"
              y="3"
              width="18"
              height="18"
              rx="3"
              stroke="#fff"
              strokeWidth="1.8"
            />
            <path
              d="M7 12h10M7 8h10M7 16h6"
              stroke="#fff"
              strokeWidth="1.8"
              strokeLinecap="round"
            />
          </svg>
          <span style={{ color: "#fff", fontSize: "0.95rem", fontWeight: 600 }}>
            MyDoshBox Escrow Agreement
          </span>
        </Modal.Title>
      </Modal.Header>

      <div ref={agreementRef}>
        {/* Meta strip */}
        <div
          style={{
            background: "#f9fafb",
            borderBottom: "1px solid #e5e7eb",
            padding: "14px 24px",
          }}
        >
          <div className="row g-3">
            <div className="col-4">
              <small
                className="text-muted d-block"
                style={{ fontSize: "0.7rem" }}
              >
                Agreement date
              </small>
              <span style={{ fontSize: "0.8rem", fontWeight: 600 }}>
                {agreementDate}
              </span>
            </div>
            <div className="col-4">
              <small
                className="text-muted d-block"
                style={{ fontSize: "0.7rem" }}
              >
                Transaction ID
              </small>
              <span
                style={{
                  fontSize: "0.78rem",
                  fontWeight: 600,
                  fontFamily: "monospace",
                }}
              >
                {shortId}…
              </span>
            </div>
            <div className="col-4">
              <small
                className="text-muted d-block"
                style={{ fontSize: "0.7rem" }}
              >
                Total value
              </small>
              <span
                style={{
                  fontSize: "0.8rem",
                  fontWeight: 600,
                  color: "#006747",
                }}
              >
                ₦{transactionTotal.toLocaleString()}
              </span>
            </div>
          </div>
        </div>

        <Modal.Body
          style={{ padding: "24px", fontSize: "0.875rem", lineHeight: 1.7 }}
        >
          <p style={{ color: "#374151" }}>
            This Escrow Agreement ("Agreement") is entered into on{" "}
            <strong>{agreementDate}</strong> between:
          </p>

          {/* Parties */}
          <div className="row g-2 mb-3">
            <div className="col-md-6">
              <div
                style={{
                  background: "#f9fafb",
                  border: "1px solid #e5e7eb",
                  borderRadius: 8,
                  padding: "12px 14px",
                }}
              >
                <small
                  className="text-muted d-block"
                  style={{
                    fontSize: "0.7rem",
                    textTransform: "uppercase",
                    letterSpacing: "0.5px",
                  }}
                >
                  Buyer
                </small>
                <span style={{ fontSize: "0.83rem", fontWeight: 600 }}>
                  {buyerEmail}
                </span>
              </div>
            </div>
            <div className="col-md-6">
              <div
                style={{
                  background: "#f9fafb",
                  border: "1px solid #e5e7eb",
                  borderRadius: 8,
                  padding: "12px 14px",
                }}
              >
                <small
                  className="text-muted d-block"
                  style={{
                    fontSize: "0.7rem",
                    textTransform: "uppercase",
                    letterSpacing: "0.5px",
                  }}
                >
                  Seller / Vendor
                </small>
                <span style={{ fontSize: "0.83rem", fontWeight: 600 }}>
                  {vendorName}
                </span>
                <small
                  className="text-muted d-block"
                  style={{ fontSize: "0.75rem" }}
                >
                  {vendorEmail}
                </small>
              </div>
            </div>
          </div>

          {/* Items */}
          <div
            style={{
              background: "#f9fafb",
              border: "1px solid #e5e7eb",
              borderRadius: 8,
              padding: "12px 14px",
              marginBottom: 20,
            }}
          >
            <small
              className="text-muted d-block mb-2"
              style={{
                fontSize: "0.7rem",
                textTransform: "uppercase",
                letterSpacing: "0.5px",
              }}
            >
              Items covered by this agreement
            </small>
            {products.map((p, i) => (
              <div
                key={i}
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  padding: "6px 0",
                  borderBottom:
                    i < products.length - 1 ? "1px solid #e5e7eb" : "none",
                  fontSize: "0.83rem",
                }}
              >
                <span style={{ color: "#111827" }}>{p.name}</span>
                <span style={{ fontWeight: 600 }}>
                  ₦{Number(p.price).toLocaleString()} × {p.quantity}
                </span>
              </div>
            ))}
            <div
              style={{
                display: "flex",
                justifyContent: "space-between",
                paddingTop: 8,
                marginTop: 4,
                borderTop: "1px solid #e5e7eb",
                fontSize: "0.8rem",
                color: "#6b7280",
              }}
            >
              <span>Platform commission (1%)</span>
              <span>₦{commission.toFixed(2)}</span>
            </div>
            <div
              style={{
                display: "flex",
                justifyContent: "space-between",
                paddingTop: 6,
                fontSize: "0.83rem",
                fontWeight: 600,
                color: "#006747",
              }}
            >
              <span>Total payable</span>
              <span>₦{transactionTotal.toLocaleString()}</span>
            </div>
          </div>

          {/* Delivery info strip */}
          <div
            style={{
              background: "#ECFDF5",
              border: "1px solid #6EE7B7",
              borderRadius: 8,
              padding: "10px 14px",
              marginBottom: 20,
              fontSize: "0.83rem",
              color: "#065F46",
            }}
          >
            <strong>Delivery address:</strong> {deliveryAddress} &nbsp;·&nbsp;
            <strong>Expected delivery:</strong> {deliveryDisplay}
          </div>

          {/* Agreement clauses */}
          {[
            {
              num: "1",
              title: "Purpose",
              body: `MyDoshBox acts as a neutral escrow agent to hold funds paid by the Buyer until the terms of this agreement are fulfilled by the Seller. Neither party shall have direct access to the held funds except as described herein. The escrow service is provided solely to facilitate secure transactions between private parties.`,
            },
            {
              num: "2",
              title: "Buyer obligations",
              body: `The Buyer (${buyerEmail}) agrees to pay the total amount of ₦${transactionTotal.toLocaleString()} into escrow before the Seller ships the goods. The Buyer must confirm receipt of the items listed above within 48 hours of delivery, or raise a formal dispute through the MyDoshBox platform. Failure to act within this window may result in automatic release of funds to the Seller.`,
            },
            {
              num: "3",
              title: "Seller obligations",
              body: `The Seller (${vendorName}) agrees to prepare and ship all items listed in this agreement within the agreed delivery timeframe after payment confirmation. The Seller must provide valid shipment tracking information through the MyDoshBox dashboard. Failure to ship within the agreed timeline, or delivery of goods materially different from those described, may result in a full or partial refund to the Buyer.`,
            },
            {
              num: "4",
              title: "Disputes",
              body: `Either party may raise a dispute through the MyDoshBox platform at any stage of the transaction. A dispute triggers a hold on all funds and may be escalated to a MyDoshBox-appointed mediator. The mediator's decision is final and binding on both parties. Both parties agree to cooperate fully and in good faith during any dispute resolution process.`,
            },
            {
              num: "5",
              title: "Fund release",
              body: `Funds are released to the Seller only upon the Buyer's explicit confirmation of satisfactory delivery. In the event of a dispute ruled in the Buyer's favour, a full or partial refund will be issued. MyDoshBox retains a 1% platform commission (₦${commission.toFixed(2)}) on the product total as a service fee, deducted from the Buyer's payment.`,
            },
            {
              num: "6",
              title: "Liability",
              body: `MyDoshBox is not a party to the underlying sale transaction and bears no liability for the quality, fitness, or legality of the goods exchanged. MyDoshBox's liability is limited solely to the management of escrowed funds in accordance with this agreement.`,
            },
            {
              num: "7",
              title: "Governing terms",
              body: `This Agreement is governed by MyDoshBox's Terms of Service and applicable laws of the Federal Republic of Nigeria. By proceeding with payment, both parties confirm they have read, understood, and accepted the terms of this Agreement.`,
            },
          ].map((clause) => (
            <div key={clause.num} style={{ marginBottom: 16 }}>
              <p
                style={{
                  fontWeight: 600,
                  color: "#111827",
                  margin: "0 0 6px",
                  fontSize: "0.875rem",
                }}
              >
                {clause.num}. {clause.title}
              </p>
              <p style={{ color: "#374151", margin: 0 }}>{clause.body}</p>
            </div>
          ))}
        </Modal.Body>
      </div>

      <Modal.Footer
        style={{ borderTop: "1px solid #e5e7eb", padding: "14px 24px" }}
      >
        <div className="d-flex gap-2 w-100 justify-content-between">
          <div className="d-flex gap-2">
            <button
              onClick={handlePrint}
              style={{
                padding: "9px 18px",
                background: "transparent",
                border: "1px solid #d1d5db",
                borderRadius: 8,
                fontSize: "0.875rem",
                color: "#374151",
                cursor: "pointer",
                display: "flex",
                alignItems: "center",
                gap: "8px",
                transition: "all 0.2s ease",
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.background = "#f3f4f6";
                e.currentTarget.style.borderColor = "#9ca3af";
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.background = "transparent";
                e.currentTarget.style.borderColor = "#d1d5db";
              }}
            >
              <FaPrint size={14} />
              Print Agreement
            </button>

            <button
              onClick={handleSaveAsPDF}
              style={{
                padding: "9px 18px",
                background: "transparent",
                border: "1px solid #d1d5db",
                borderRadius: 8,
                fontSize: "0.875rem",
                color: "#374151",
                cursor: "pointer",
                display: "flex",
                alignItems: "center",
                gap: "8px",
                transition: "all 0.2s ease",
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.background = "#f3f4f6";
                e.currentTarget.style.borderColor = "#9ca3af";
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.background = "transparent";
                e.currentTarget.style.borderColor = "#d1d5db";
              }}
            >
              <FaDownload size={14} />
              Save as PDF
            </button>
          </div>

          <div className="d-flex gap-2">
            <button
              onClick={onClose}
              style={{
                padding: "9px 18px",
                background: "transparent",
                border: "1px solid #d1d5db",
                borderRadius: 8,
                fontSize: "0.875rem",
                color: "#6b7280",
                cursor: "pointer",
              }}
            >
              Close
            </button>
            <button
              onClick={onClose}
              style={{
                padding: "9px 20px",
                background: "#006747",
                border: "none",
                borderRadius: 8,
                fontSize: "0.875rem",
                fontWeight: 600,
                color: "#fff",
                cursor: "pointer",
              }}
            >
              I have read and accept this agreement
            </button>
          </div>
        </div>
      </Modal.Footer>
    </Modal>
  );
};

export default EscrowAgreementModal;
